services:
  mongodb:
    image: mongo:8
    container_name: equitrade-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - equitrade-mongodb-data:/data/db

volumes:
  equitrade-mongodb-data:
